boostorg/interprocess

include/boost/interprocess/exceptions.hpp

Hi,
As already explained in the boost::config documentation, any boost exception should be forced to be visible no matter which compiler flags are used. See http://www.boost.org/doc/libs/1_58_0/libs/config/doc/html/boost_config/boost_macro_reference.html#boost_config.boost_macro_reference.macros_for_libraries_with_separate_source_code.macros_controlling_shared_library_symbol_visibility
Cheers,
Romain

Fix exception visibility.

---

include/boost/interprocess/detail/config_begin.hpp
include/boost/interprocess/detail/config_end.hpp

Shane wrote:
> I found another issue with a bad compiler version check in boost/interprocess/detail/config_begin.hpp before using "#pragma GCC diagnostic push", which, for GCC, is only available at version 4.6.0 and later. Since I'm using GCC 4.4.7, my compile fails.
Updated the version check to only fire on 4.6 and later.

Update gcc version diagnostic pragmas; reported by Shane Turner

---

include/boost/interprocess/xsi_key.hpp

Allow user to specify an exact value for `xsi_key`. New constructor is marked as explicit to avoid ambiguity with `shmid`, since `key_t` is actually `int`.

Add xsi_key(key_t) constructor

---

include/boost/interprocess/offset_ptr.hpp

offset_ptr<T, ...>::rebind<U> must be offset_ptr<U, ...> directly
to avoid breaking older pointer_traits implementations (like in Visual Studio 2015),
'other' is added as typedef so offset_ptr<T, ...>::rebind< U >::other still works

Conform to std::pointer_traits requirements

---

include/boost/interprocess/detail/utilities.hpp
include/boost/interprocess/offset_ptr.hpp

See individual commits for details.

"explicit cast to derived class" and "64/32 bit processes sharing"

---

example/Jamfile.v2
test/Jamfile.v2

Replaced \<host-os\> with \<target-os\> so that the correct options for the target are selected when cross-compiling. When not cross-compiling, it makes no difference as target-os by default mirrors host-os.
Without this, I get the linker error "cannot find -lrt" on my regression test runner for QNX 6.6.0 which is cross-compiling from Linux to QNX.

Fixed options for cross-compilation.

---

example/doc_multi_index.cpp

Updates the example for `boost::multi_index` to retire [the legacy key extraction macro](http://www.boost.org/doc/libs/1_63_0/libs/multi_index/doc/reference/key_extraction.html#boost_multi_index_member), which has been designated in `multi_index` as "a portability mechanism for legacy compilers where `member` could not be supported."

Update example to use multi_index::member instead of BOOST_MULTI_INDEX_MEMBER

---

doc/interprocess.qbk

The current examples look strange since the C++-style comments result in the rest of the line being completely commented-out:
This commit changes the way those parameters are documented to make them consistent with the rest of the documentation.
Note that I was unable to test this change because I wasn't able to generate the Boost documentation locally.

Fix misformatted code samples in the documentation

---

include/boost/interprocess/offset_ptr.hpp
include/boost/interprocess/smart_ptr/intrusive_ptr.hpp
test/intrusive_ptr_test.cpp

… and made its methods noexcept. I hope the BOOST_NOEXCEPT macro is correct for backwards compatibility.
Also added reset() method in line with std::shared_ptr::reset / unique_ptr::reset. In several places of our code I've found this addition useful because the caller had to lock the shared_heap before releasing a reference, so just letting ~intrusive_ptr release the ptr was not correct.

Make intrusive_ptr move constructible/assignable 

---

include/boost/interprocess/detail/atomic.hpp
include/boost/interprocess/detail/os_thread_functions.hpp
include/boost/interprocess/detail/workaround.hpp

- add CPU count
- provide OS specific atomics (when none with compiler)
- don't use XSI

Update VxWorks support

---

include/boost/interprocess/sync/spin/mutex.hpp

Avoid deadlock in named_condition::notify_one when BOOST_INTERPROCESS_ENABLE_TIMEOUT_WHEN_LOCKING is defined
Fixes issue #69

Fix deadlock in named_condition::notify_one

---

include/boost/interprocess/sync/windows/winapi_wrapper_common.hpp

United handling of wait_for_single_object (WaitForSingleObject).
Fixes #9284.

United handling of wait_for_single_object

---

include/boost/interprocess/detail/os_file_functions.hpp
include/boost/interprocess/errors.hpp
include/boost/interprocess/exceptions.hpp
include/boost/interprocess/shared_memory_object.hpp

Use BOOST_OVERRIDE to fix GCC -Wsuggest-override and Clang-tidy modernize-use-override warnings.
Also fix Clang-tidy modernize-deprecated-headers and modernize-use-bool-literals warnings.
Alphabetical order of STL headers.

Use BOOST_OVERRIDE

---

include/boost/interprocess/detail/win32_api.hpp

MinGW has nonstandard definition of `PSECURITY_DESCRIPTOR`, which requires a cast when calling WinAPI functions `InitializeSecurityDescriptor` and `SetSecurityDescriptorDacl`. This is done by Boost.WinAPI wrapper functions.
Fixes https://github.com/boostorg/interprocess/issues/118.
Also, fixed the `initialized` flag not being set correctly after `interprocess_all_access_security` initialization completes.

Fix mingw compile error

---

example/comp_doc_message_queueB.cpp

Fix comment in accordance with the original type description from the: boost/interprocess/creation_tags.hpp.

Fix trivial typo in comment for example for message queue

---

include/boost/interprocess/streams/bufferstream.hpp

boost/interprocess/streams/bufferstream.hpp(135): warning C4242: '=': conversion from 'int' to '_Elem', possible loss of data
with
[
_Elem=char
]

Correct MSVC compilation warning

---

doc/interprocess.qbk

add the word "bit" to clarify two sentences.

fix wording about 32 bit systems.

---

doc/interprocess.qbk

References for named_condition_any point to named_condition now corrected to named_condition_any.

Correct references for named_condition_any

---

include/boost/interprocess/smart_ptr/shared_ptr.hpp
test/shared_ptr_test.cpp

Without `const` the new test fails with the following error:
```
terminate called after throwing an instance of 'boost::interprocess::bad_weak_ptr'
what():  boost::interprocess::bad_weak_ptr
Aborted (core dumped)
```

properly initilize enable_shared_from_this if the type is const

---

include/boost/interprocess/permissions.hpp

Boost 1.78.0 fails to build on musl-based systems because musl does
not include sys/stat.h by default.
Fixes #161 ("Boost compiler error")

Fix missing sys/stat.h include on musl-based systems

---

include/boost/interprocess/windows_shared_memory.hpp

Fixes issue #153.
Restores the original behavior (pre 140b50efb3281fa3898f3a4cf939cfbda174718f).
If `filename` is provided as a wide string, then `get_name()` will return an unspecified pointer.

Fixing windows_shared_memory::get_name()

---

doc/interprocess.qbk

Trivial typo fix for the word "shared" in docs.

interprocess.qbk: fix minor typo

---

include/boost/interprocess/mem_algo/rbtree_best_fit.hpp

The assertion in the ```check_sanity()``` function causes the function to crash without releasing the ```shared mutex```.
The assertion is redundant due to ```alignment check``` in the following lines that returns ```false``` in case of failure and releases the ```shared mutex```.
PR for [Issue 177](https://github.com/boostorg/interprocess/issues/177)

remove redundent assertion alignment check to avoid exiting the function without releasing scoped mutex

---

include/boost/interprocess/detail/workaround.hpp

I met an error
```
wasm-ld: error: build/sysroot/usr/local/lib/librime.a(mapped_file.cc.o): undefined symbol: shmdt
```
From https://stackoverflow.com/questions/60285563/shared-memory-sys-shm-h-with-emscripten it seems emscripten doesn't support shm.
I applied this patch so it linked successfully.

Fix: emscripten doesn't support shm

---

include/boost/interprocess/detail/windows_intermodule_singleton.hpp

I reproduced [this](https://github.com/cmazakas/unordered/actions/runs/9035399323/job/24830087065#step:6:1478) failing CI run of Boost.Unordered locally, and found that it gave me a pop-up coming from Boost.Interprocess.
After the change in this PR, the issue no longer occurs.

Fix Windows RTC issue

---

CMakeLists.txt

fixes https://github.com/boostorg/lockfree/actions/runs/7236168354/job/19714404066

cmake: link system libraries

---

include/boost/interprocess/streams/vectorstream.hpp

File sizes larger than INT_MAX cause segmentation faults, due to the use of `pbump/gbump`, which only support `int` increments.
Rewrite `int`-based offset adjustments to use streamoff offsets instead.
Fixes #190.

vectorstream: support file sizes larger than INT_MAX

---

include/boost/interprocess/detail/managed_open_or_create_impl.hpp
include/boost/interprocess/ipc/message_queue.hpp

The goal of this feature is to allow to map message_queue in anonymous shared memory - to make communication of forked processes easy. There is no need to create a "file" mapping in this scenario - there is no issues with privileges and memory is not exposed.

Allow to map message_queue in anonymous memory

---

include/boost/interprocess/sync/windows/sync_utils.hpp

This fixes https://github.com/boostorg/interprocess/issues/192 and https://github.com/boostorg/interprocess/issues/210 (which seem to describe the same bug).
Here's the code I'm testing this on. I'm using VS 2022 (though some coworkers with the same compiler can't reproduce, I'm not entirely sure why)
```cpp
#define BOOST_INTERPROCESS_FORCE_NATIVE_EMULATION 1 // This is important, doesn't crash otherwise.
#include <boost/interprocess/allocators/allocator.hpp>
#include <boost/interprocess/managed_windows_shared_memory.hpp>
#include <boost/interprocess/smart_ptr/unique_ptr.hpp>
#include <iostream>
int main()
{
std::cout << "Before\n";
{
namespace bip = boost::interprocess;
// Destructor of `x` crashes.
auto x = bip::managed_windows_shared_memory( bip::open_or_create, "blah", …
```

Fix iterator invalidation bug.

---

include/boost/interprocess/detail/os_file_functions.hpp

Failure seen in [unordered#274](https://github.com/boostorg/unordered/pull/274)

Fix Wshadow warning for Clang <= 4.0

---

include/boost/interprocess/detail/segment_manager_helper.hpp

This issue was seen in boostorg/unordered#287

Fix shadowing warning

---

include/boost/interprocess/interprocess_printers.hpp

Related to boostorg/unordered#294, boostorg/unordered#295
This fix is based on ned14/outcome#308

Fix inline assembly for armv7 target

---

include/boost/interprocess/detail/file_wrapper.hpp

Similar to commit `4e2c06b24211e4983dad95d4b1035d1e0602490d`. `m_mode` is not initialized in `file_wrapper`'s move constructor. UBSan error was triggered on this line in `interprocess/include/boost/interprocess/detail/managed_open_or_create_impl.hpp`:
```cpp
if(StoreDevice){                                                                                                                  
this->DevHolder::get_device() = boost::move(dev);                                                                                                                                                                                                                       
}                                                                                                                                 
```
My …

Fix UBSan runtime error (load of 'boost::interprocess::mode_t')
